### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by subu250** [jeliceiri/MyPlacesTracker#10]
# Design/Code Review 

#### Reviewer: Subheksha Karki

@pawaitemadisoncollege- Project is almost completed. Awesome work.

​
|Areas for Improvement|Criteria|Items Met or Exceeded|
|--------|---------|---------------|
||**Project effectively utililizes the technologies and technques specified in the project objectives**||
|| Planned MVP Functionality | |MVP functionality used as defined.
|| Logging framework used, i.e., no System.out.println() or printStacktrace() statements.|Logging framework used in the validation
|| Hibernate used for all data access. | Hibernate used as well hibernate validation.
|| Authentication implemented. | Authentication implemented in the project.
|| Consumes at least one web service or public api using Java. | public api used.
|| Application is database-driven using full CRUD.| Yes, all CRUD functionality is used.
|| Database includes multiple one to many relationships. |  Yes, project meets the requirement.
|| Deployed to AWS for public access. |Yes, project deployed to AWS.
|| Implements best practices (for example, data validation)  | Data validation added to the project.
|| **Synthesis of multiple concepts in unfamiliar situations requiring research beyond the scope of the class**||
||Experiments individually, exhibits independence and drive, shows originality in the solution.||
||Implemented technologies or techniques not covered in course materials. ||
||**Code quality - Evaluate  code quality for the following and identify specific areas for improvement (class, method or line number). Be sure to list which code quality plugins/tools you used to assist with this analysis**||
|| Single-purpose methods ||
|| Well-structured project||
|| Descriptive naming of packages, classes, methods, variables ||
||Classes appropriately-sized  (no monster classes)||
|| CPD (copy paste detection, meaning are the same lines of code repeated?||
|| Are there candidates for super/subclass relationships, abstract classes, interfaces ||||are any values hard-coded that should be in a properties file? ||
||Proper exception handling ||
||Proper error reporting to the user - custom erro pages?|| 
||Code documentation|| 
|| Is there code in the servlet doGet/doPost that should be refactored into testable classes or methods? ||
||Evaluate the JSPs for templating, data validation, overall look and feel.| |
|| JSPs use JSTL and EL, no java code ||| |
|| Unit tests are truly a unit test rather than a high level functional test || 
||Test data is appropriately cleaned up or handled|| 
||There is full coverage of methods that perform business logic or utility functions||
||Redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After||
||Other comments/notes?| |
||**Demonstrates initiative and thoughtful planning to leverage available resources (time, equipment, external expertise) to meet milestones and project objectives.** ||
|| **Evidence of significant revision and incorporation of feedback.** ||
|| **Project complexity** ||
|| **Additional Comments** | Very nicely done and presented. Great job and Good luck.

**Comment by pawaitemadisoncollege** [comment]
@subu250 Is this complete? It seems to be missing feedback on the code quality section.
