### ISSUE TITLE
Code Review #1

### ISSUE THREAD

**Issue by AliviaK** [jeliceiri/MyPlacesTracker#4]
# Design/Code Review 1

### Reviewer: Alivia Kleinfeldt

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| - Great problem statement that describes how it is a unique app<br> - Second sentence wording is a bit awkward (but I'm nitpicking because it is overall excellent)|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | - All screens appear represented with wireframes and project plan is very thorough! <br> - The wording of the user stories is unclear<br> - Was unclear if some rectangles on the trip info screen were headers or if all were buttons/would take user to different views |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| - One-to-many relationship represented<br> - Database/tables design could use a visual or written representation<br> - Are all tables and rows represented with entities? I see hospitalCapacity and weatherInfo commented out and wondered if those are features or tables to come |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage.  | - Project is well structured and well progressed! <br> - The Destination class could use unit tests<br> - I don't believe Database.java is needed anymore since your hibernate.cfg.xml contains database info (& the hibernate.cfg.xml would be good to add to .gitignore to protect your password!) |

**Comment by jeliceiri** [comment]
Thanks for the helpful comments @AliviaK!
