### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by AliviaK** [jeliceiri/MyPlacesTracker#9]
# Design/Code Review 2

#### Reviewer: Alivia Kleinfeldt 

@pawaitemadisoncollege

|Areas for Improvement|Criteria|Items Met or Exceeded|
|--------|---------|---------------|
| | **Project effectively utilizes the technologies and techniques specified in the project objectives** ||
| | Planned MVP Functionality | Meets MVP |
| | Logging framework used, i.e., no System.out.println() or printStacktrace() statements. | Logging looks good | 
| | Hibernate used for all data access. | Hibernate used |
| | Authentication implemented. | AWS login was demonstrated |
| | Consumes at least one web service or public api using Java. | Smartystreets and covidactnow both used |
| | Application is database-driven using full CRUD. | Full CRUD achieved and app is database-driven |
| | Database includes multiple one to many relationships. | Accomplished with users and trips |
| | Deployed to AWS for public access. | Deployed and accessible on AWS |
| | Implements best practices (for example, data validation)  | Data validation implemented, project structure looks good code looks clean |
| | **Synthesis of multiple concepts in unfamiliar situations requiring research beyond the scope of the class** ||
| | Experiments individually, exhibits independence and drive, shows originality in the solution. | Idea is unique and accomplishes a great deal |
| | Implemented technologies or techniques not covered in course materials. | Two APIs consumed and materialize used for style  |
| | **Code quality - Evaluate  code quality for the following and identify specific areas for improvement (class, method or line number). Be sure to list which code quality plugins/tools you used to assist with this analysis** ||
| | Single-purpose methods | No issues here |
|  | Well-structured project | Structure looks good according to intellij built in tests and QAPlug |
| | Descriptive naming of packages, classes, methods, variables | Good, descriptive naming used |
| | Classes appropriately-sized  (no monster classes) | Class size is good |
| | CPD (copy paste detection, meaning are the same lines of code repeated? | None detected |
| | Are there candidates for super/subclass relationships, abstract classes, interfaces | None that I saw|||are any values hard-coded that should be in a properties file? ||
| | Proper exception handling | Yes |
| | Proper error reporting to the user - custom error pages? | I see an error page | 
| | Code documentation | Well documented and javadoc used | 
| | Is there code in the servlet doGet/doPost that should be refactored into testable classes or methods? | Servlets look good |
| | Evaluate the JSPs for templating, data validation, overall look and feel. | Validation used and JSPs have consistent look and feel, which is sleek! |
| | JSPs use JSTL and EL, no java code | JSTL and EL used || |
| | Unit tests are truly a unit test rather than a high level functional test | Testing is well done and thorough | 
| | Test data is appropriately cleaned up or handled | Test database used | 
| | There is full coverage of methods that perform business logic or utility functions | Test screenshot shows full coverage |
| | Redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After | Uses @BeforeAll in tests |
| Could clean up by getting rid of api assignment directory and files | Other comments/notes? | Very impressive and nice looking application, congratulations! |
| | **Demonstrates initiative and thoughtful planning to leverage available resources (time, equipment, external expertise) to meet milestones and project objectives.** | Evident that lots of time and planning went into this, and is well documented |
| | **Evidence of significant revision and incorporation of feedback.** | Feedback incorporated and resolved from closed github issues |
| | **Project complexity** | A complex and thorough project that consumes multiple resources |
| | **Additional Comments** | Ran QAPlug on code with minimal suggestions for improvement; this project looks excellent! |

**Comment by jeliceiri** [comment]
@AliviaK Thank you for reviewing this project! Fyi, I added some comments to the rest service, as I'm thinking of keeping it here for the time being with plans of returning to it and expanding it with Swagger and more endpoints. Also, I do have an error page but am using error messages in individual jsp's. So, I can probably get rid of that if not used, I'm glad you pointed it out! Thanks again!

**Comment by pawaitemadisoncollege** [comment]
@jeliceiri the error page _might_ be good for error conditions that aren't handled - 404s or some weird 500 that you don't expect...

**Comment by jeliceiri** [comment]
@pawaitemadisoncollege Sounds good, will keep it there and utilize it!
